USE [eCampus]
GO

/****** Object:  Table [dbo].[MST_ACTIVITY]    Script Date: 12-02-2019 20:57:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MST_ACTIVITY](
	[ACT_ID] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[ACT_NAME] [nvarchar](100) NOT NULL,
	[ACT_STATUS] [nvarchar](100) NULL,
	[ACT_TYPE] [nvarchar](100) NULL,
	[ACT_START] [datetime] NOT NULL,
	[ACT_END] [datetime] NULL,
	[IS_ACTIVE] [char](1) NOT NULL,
	[CUSTOMER_ID] [nvarchar](100) NOT NULL,
	[USER_ID] [nvarchar](100) NOT NULL,
	[CREATED_BY] [nvarchar](150) NULL,
	[CREATED_WHEN] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




USE [eCampus]
GO

/****** Object:  Table [dbo].[MST_COURSE]    Script Date: 12-02-2019 20:57:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MST_COURSE](
	[COURSE_CODE] [nvarchar](100) NOT NULL,
	[COURSE_NAME] [nvarchar](100) NOT NULL,
	[NO_SEMESTER] [nvarchar](100) NULL,
	[IS_ACTIVE] [char](1) NOT NULL,
	[CUSTOMER_ID] [nvarchar](100) NOT NULL,
	[USER_ID] [nvarchar](100) NOT NULL,
	[CREATED_BY] [nvarchar](150) NULL,
	[CREATED_WHEN] [datetime] NULL,
 CONSTRAINT [pk_products_pid] PRIMARY KEY CLUSTERED 
(
	[COURSE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




USE [eCampus]
GO
/****** Object:  StoredProcedure [dbo].[SP_ADD_ACTIVITY]    Script Date: 12-02-2019 20:58:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER  PROCEDURE [dbo].[SP_ADD_ACTIVITY]
(
    @P_ACT_NAME			NVARCHAR(200),
    @P_ACT_STATUS		NVARCHAR(500),
	@P_ACT_TYPE			NVARCHAR(500),
    @P_ACT_START		NVARCHAR(200),
	@P_ACT_END			NVARCHAR(200),
	@P_FLAG				CHAR(1),
	@P_CUSTOMER_ID		NVARCHAR(100),
	@P_USER_ID			NVARCHAR(100), 
	@P_RSP_FLAG			CHAR   OUTPUT,
    @P_RSP_MSG          NVARCHAR(200) OUTPUT
	)
AS
	IF @P_FLAG	=	'A' 
	BEGIN
       IF EXISTS (SELECT * FROM MST_ACTIVITY WHERE UPPER(ACT_NAME) = UPPER(@P_ACT_NAME))                
			BEGIN
				SET @P_FLAG		=	'F';
				SET @P_RSP_MSG	=	'Activity Name already exist in a system.';
			END
	   ELSE            
			BEGIN
			INSERT INTO MST_ACTIVITY (ACT_NAME,ACT_STATUS,ACT_TYPE,ACT_START,ACT_END,IS_ACTIVE,CUSTOMER_ID,USER_ID)
			VALUES(@P_ACT_NAME,@P_ACT_STATUS,@P_ACT_TYPE,@P_ACT_START,@P_ACT_END,@P_FLAG,@P_CUSTOMER_ID,@P_USER_ID)
					IF @@ROWCOUNT > 1
						BEGIN
							SET @P_FLAG		=	'S';
							SET @P_RSP_MSG	=	'Activity added successfully.';
							SET NOCOUNT ON;  
								SELECT ACT_NAME,ACT_STATUS,ACT_TYPE ,ACT_START,ACT_END FROM MST_ACTIVITY;
						END
					ELSE
						BEGIN
							SET @P_FLAG		=	'F';
							SET @P_RSP_MSG	=	'Something went wrong while inserting. Please try again later.';
						END
				END			
		END
	ELSE IF @P_FLAG='M'
	BEGIN
	UPDATE MST_ACTIVITY SET ACT_STATUS=@P_ACT_STATUS, ACT_TYPE=@P_ACT_TYPE, ACT_START=@P_ACT_START,ACT_END=@P_ACT_END,IS_ACTIVE='Y',CREATED_BY='',CREATED_WHEN=''
	WHERE ACT_NAME= @P_ACT_NAME;
	SET @P_FLAG='S';
	SET @P_RSP_MSG='Activity Updated Successfully';
	SET NOCOUNT ON;  
	SELECT ACT_NAME,ACT_STATUS,ACT_TYPE ,ACT_START,ACT_END FROM MST_ACTIVITY;
	END
	ELSE
	BEGIN
	DELETE FROM MST_ACTIVITY WHERE ACT_NAME= @P_ACT_NAME;
	SET @P_FLAG='S';
	SET @P_RSP_MSG='Activity Deleted Successfully';
	SET NOCOUNT ON;  
	SELECT ACT_NAME,ACT_STATUS,ACT_TYPE ,ACT_START,ACT_END FROM MST_ACTIVITY;
	END


	
	USE [eCampus]
GO
/****** Object:  StoredProcedure [dbo].[SP_ADD_COURSE]    Script Date: 12-02-2019 20:58:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER  PROCEDURE [dbo].[SP_ADD_COURSE]
(
    @P_COURSE_CODE		NVARCHAR(200),
    @P_COURSE_NAME		NVARCHAR(500),
	@P_NO_SEMESTER		NVARCHAR(500),
	@P_FLAG				CHAR(50),
	@P_CUSTOMER_ID		NVARCHAR(100),
	@P_USER_ID			NVARCHAR(100),  
	@P_RSP_FLAG			CHAR(50)   OUTPUT,
    @P_RSP_MSG          NVARCHAR(200) OUTPUT
	)
AS
	IF @P_FLAG='A' 
	BEGIN
       IF EXISTS (SELECT * FROM MST_COURSE WHERE UPPER(COURSE_CODE) = UPPER(@P_COURSE_CODE))                
			BEGIN
				SET @P_RSP_FLAG		=	'F';
				SET @P_RSP_MSG	=	'Course Name already exist in a system.';
			END
	   ELSE            
			BEGIN
				INSERT INTO MST_COURSE(COURSE_CODE,COURSE_NAME,NO_SEMESTER,CUSTOMER_ID,USER_ID,IS_ACTIVE) 
				VALUES(@P_COURSE_CODE,@P_COURSE_NAME,@P_NO_SEMESTER,@P_CUSTOMER_ID,@P_USER_ID,'Y')
					IF @@ROWCOUNT > 1
						BEGIN
							SET @P_RSP_FLAG		=	'S';
							SET @P_RSP_MSG	=	'Course added successfully.';
							SET NOCOUNT ON;  
							SELECT COURSE_CODE,COURSE_NAME,NO_SEMESTER FROM MST_COURSE;
						END
					ELSE
						BEGIN
							SET @P_RSP_FLAG		=	'F';
							SET @P_RSP_MSG	=	'Something went wrong while inserting. Please try again later.';
						END
				END			
		END
	  ELSE IF @P_FLAG='M'
		BEGIN
			UPDATE MST_COURSE SET COURSE_NAME=@P_COURSE_NAME, NO_SEMESTER=@P_NO_SEMESTER,IS_ACTIVE='Y',CREATED_BY='',CREATED_WHEN=''
			WHERE COURSE_CODE= @P_COURSE_CODE;
				SET @P_RSP_FLAG='S';
				SET @P_RSP_MSG='Course Updated Successfully';
			SET NOCOUNT ON;  
			SELECT COURSE_CODE,COURSE_NAME,NO_SEMESTER FROM MST_COURSE;
		END
	ELSE
		BEGIN
			DELETE FROM MST_COURSE WHERE COURSE_CODE= @P_COURSE_CODE;
			SET @P_RSP_FLAG='S';
			SET @P_RSP_MSG='Course Deleted Successfully';
		SET NOCOUNT ON;  
		SELECT COURSE_CODE,COURSE_NAME,NO_SEMESTER FROM MST_COURSE;
	END
